version: '3'

services:
  app:
    container_name: api
    build: .
    expose:
      - "8096:8096"
    restart: on-failure
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./sql/init:/docker-entrypoint-initdb.d
    ports:
      - "33969:3306"